name = "react_native"
entrypoint = "index.js"
extensions = [
  "js"
]
packages = []
setup = [
  "yarn global add jest",
  "yarn"
]

[run]
command = [
  "jest",
  "--colors",
  "--config",
  "/home/runner/config.json"
]
